Game
MissMelisa/game pull request #1
Opened 2021-05-17 17:02 UTC by MissMelisa

Create main page of the game

2021-05-18 20:03 UTC, falecci commented on src/Components/Game/index.jsx
> +  let computerChoice = options[Math.floor(Math.random() * 3)];
```suggestion
  let computerChoice = options[Math.floor(Math.random() * options.length)];
```

We can change that, so instead of hardcoding this to multiply per 3, we multiply to the actual options length. In the future if we add a new option, we won't have to modify this code.

2021-05-18 20:08 UTC, falecci requested changes

2021-05-18 20:08 UTC, falecci commented on src/Components/Game/index.jsx
> +      console.log(computerNewChoice);
remove this log please

2021-05-18 20:08 UTC, falecci commented on src/Components/Game/index.jsx
> +  }
This function is called whenever we hit the `New Game` button. 

Apart from closing the modal, we should reset the state. I believe that without resetting the state, if we chose the same choice again, we will always get the same result.

That's because the `useEffect` we have in this component, runs whenever `userChoice` changes. If we don't reset it, it will never get triggered again with the same choice.

2021-05-18 20:08 UTC, falecci commented on src/Components/Game/index.jsx
> +      </Modal>
Can we move this to its own component? Something like: `GameResult` ?

2021-05-19 15:37 UTC, MissMelisa commented on src/Components/Game/index.jsx
> +  let computerChoice = options[Math.floor(Math.random() * 3)];
do it!

2021-05-19 15:37 UTC, MissMelisa commented on src/Components/Game/index.jsx
> +      console.log(computerNewChoice);
sorry! fix it!

2021-05-19 16:17 UTC, MissMelisa commented on src/Components/Game/index.jsx
> +  }
fix it

2021-05-21 14:40 UTC, falecci approved these changes

2021-05-21 18:54 UTC, merged